### ISSUE TITLE
プロジェクト全体のcssのデザイン改善案

### ISSUE THREAD

**Issue by Takedarn** [jigintern/real-2024-a#22]
# デザイン修正案
ここでは後ほど修正を検討したいデザイン案を記載します

## 全ページ共通のアイデア
まず、どのページでも左右に余白をつくってデザインに余裕を持たせたい、
- デフォルトで左右に余裕がないとデフォルトでズームされているように見える
  - 以下の画像のように黄色いところみたいな、左右にpaddingが欲しい
<img width="269" alt="sample" src="https://github.com/user-attachments/assets/c4ce1001-1957-4d8e-aaa3-6920ab57f8c8">

## footerのアイデア
- footer-itemをきちんと等間隔で置きたい

- 全体のfooterを以下のような、backgroundに白色を指定して、fotter-itemをprimary colorにするとスッキリしておしゃれになりそうな気がする
  - 個人的にはprimary colorを、今のfooterの背景色のように全面に押し出すのは野暮ったいと思う　
  　一番大事なSPボタンは以下の画像のように、常にprimary colorでいいと思います
  - これも以下の画像ままだけど、fotterとmainの間に薄いグレーのborderを入れるとスッキリしそう
![S__24133636_0](https://github.com/user-attachments/assets/3ee34c37-8327-4703-847f-0d6b03382ae4)

**Comment by isirmt** [comment]
以下のように変更

![image](https://github.com/user-attachments/assets/b3b6007b-45c0-413e-b7dd-10954bf3748c)
